config/routes.rb
Rails.application.routes.draw do

  resources :orders
  get 'home/index'

  match '/contacts',    to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  get "specialization_types/:specialization_type_id/specializations" => "application#specializations", :as => "specializations", :format => :json

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :charges

  resources :order_profiles
  resources :users

  authenticated :user do
    root 'orders#new', as: "authenticated_root"
  end

  get 'welcome/about_us'
  get 'twilio/sms', defaults: { format: 'twiml' }

  post 'get_coffee' => 'home#get_coffee', as: :get_coffee

  post 'submit_order' => 'home#submit_order', as: :submit_order

  root 'welcome#index'

end

app/models/order_profile.rb
class OrderProfile < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_one :business, through: :product
  validates :user, presence: true
end

app/controllers/order_profiles_controller.rb
class OrderProfilesController < ApplicationController
  before_action :set_order_profile, only: [:show, :edit, :update, :destroy]
  respond_to :json
  # GET /order_profiles
  # GET /order_profiles.json

  def index
    @order_profiles = current_user.order_profiles.all
  end

  # GET /order_profiles/1
  # GET /order_profiles/1.json
  def show
  end

  # GET /order_profiles/new
  def new

    # @business_names = []
    # Business.find_each do |b|
    #   @business_names << [b.name, b.id]
    # end

    # @business_json=[]
    # Business.find_each do |b|
    #   @business_json << b.to_json
    # end

    # @product_names = []
    # Product.find_each do |p|
    #   @product_names << [p.name, [p.id, p.business_id]]
    # end

    # @product_json = []
    # Product.find_each do |j|
    #   @product_json << j.to_json
    # end

    @order_profile = current_user.order_profiles.build

    @businesses = Business.find_each.as_json
    @products = Product.find_each.as_json


    end




  # GET /order_profiles/1/edit
  def edit
    @business_names = []
    Business.find_each do |b|
      @business_names << [b.name, b.id]
    end
    @product_names = []
    Product.find_each do |p|
      @product_names << [p.name, [p.id, p.business_id]]
    end
  end

  # POST /order_profiles
  # POST /order_profiles.json
  def create

    @order_profile = current_user.order_profiles.build(order_profile_params)


    respond_to do |format|
      if @order_profile.save
        format.html { redirect_to @order_profile, notice: 'Order profile was successfully created.' }
        format.json { render :show, status: :created, location: @order_profile }
      else
        format.html { render :new }
        format.json { render json: @order_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_profiles/1
  # PATCH/PUT /order_profiles/1.json
  def update
    respond_to do |format|
      if @order_profile.update(order_profile_params)
        format.html { redirect_to @order_profile, notice: 'Order profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_profile }
      else
        format.html { render :edit }
        format.json { render json: @order_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_profiles/1
  # DELETE /order_profiles/1.json
  def destroy
    @order_profile.destroy
    respond_to do |format|
      format.html { redirect_to order_profiles_url, notice: 'Order profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_profile
      @order_profile = current_user.order_profiles.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_profile_params
      params[:order_profile].permit(:name, :product_id, :address_for_delivery, :phone)

    end
end

app/views/order_profiles/_form.html.erb
<div class="text-center">
  <%= simple_form_for(@order_profile) do |f| %>

    <!-- error check -->
    <% if @order_profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order_profile.errors.count, "error") %> prohibited this order_profile from being saved:</h2>
        <ul>
        <% @order_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <!-- end error check -->

  <%= f.input :name %>
  <%= f.input :phone %>
  <%= f.input :address_for_delivery %>


  <!-- business and product select -->
  <div>
  <%= @businesses.each do |b| %>
    <table class="table table-striped table-bordered">
      <tbody>
        <tr class="rowlink">
          <td>
            <!-- display all business options -->
            <div class="dropdown">
              <a class="dropdown-toggle rowling" data-toggle="dropdown" href="#">
                <!-- business names -->
                <%= b['name']%>
              </a>
              <!-- end business option display -->

              <!-- display all products of a selected business as dropdown -->
              <ul class="dropdown-menu" role="menu" aria=labelledby="dLabel" href="#">
              <%= @products.each do |p| %>
                <% if p['business_id'] == b['id'] %>
                  <li>
                    <a class="selected_product" tabindex="-1" href="#">

                      <!-- product name -->
                      <%= p['name'] %>

                      <!-- product cost -->
                      <div class="product-cost">
                        <%= "$" %>
                        <%= number_with_precision(((p['cost_in_pennies'].to_i)/100.0), :precision => 2) %>
                      </div>
                      <!-- end product cost -->

                    </a>
                  </li>

                  <!-- invisible field used to pass selected product id to input :product_id below -->
                  <li style="visibility:hidden"><%= p['id'] %></li>

                <%end%>
              <%end%>
              </ul>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  <%end%>
  </div>

  <!-- invisible field to pass selected product id to order profile -->
  <%= f.input :product_id, :as => :hidden, :input_html => { :id => "test", :value => ""}%>

  <!-- submit button  -->
  <div class="actions">
    <%= f.submit %>
  </div>

  <!-- price explanation div (appears on hover of price in product list above) -->
  <div id="price-explanation" style="display:none; position:absolute; z-index:100; background-color:red">
    <%= "total cost = product price + 10% + tax" %>
  </div>

  <% end %>
</div>

app/views/order_profiles/index.html.erb
<div class="order-profile">
  <p id="notice"><%= notice %></p>

  <h1>Listing Order Profiles</h1>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>Name</td>
          <td>Product</td>
          <td>Business</td>
          <td></td>
        </tr>
      <% @order_profiles.each do |order_profile| %>
        <tr>
          <td><%= order_profile.name %></td>
          <td><%= order_profile.product.try(:name) %></td>
          <td><%= order_profile.business.try(:name) %></td>
          <td><%= link_to 'Show', order_profile %></td>
          <td><%= link_to 'Edit', edit_order_profile_path(order_profile) %></td>
          <td><%= link_to 'Destroy', order_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Order Profile', new_order_profile_path %>
</div>

app/views/order_profiles/new.html.erb
<div class="order-profile">
  <h1>New Order Profile</h1>

  <%= render 'form' %>

  <%= link_to 'Back', order_profiles_path %>
</div>

app/views/order_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<br><br><br>


<!--Temporarily styling for visual ease -->
<style type="text/css">
  table {
    margin: 15px;
  }
  td {
    padding-left: 20px;
  }
</style>


<table>
  <tr>
    <td>Profile Name</td>
    <td>Phone Number</td>
    <td>Delivery Address</td>
    <td>Business</td>
    <td>Product</td>
  </tr>
  <tr>
    <td><%=@order_profile.name %></td>
    <td><%=@order_profile.phone %></td>
    <td><%=@order_profile.address_for_delivery %></td>
    <td><%=@order_profile.business.name %></td>
    <td><%=@order_profile.product.name %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_order_profile_path(@order_profile) %> |
<%= link_to 'Back', order_profiles_path %>