config/routes.rb
Rails.application.routes.draw do

  resources :orders
  get 'home/index'

  match '/contacts',    to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  get "specialization_types/:specialization_type_id/specializations" => "application#specializations", :as => "specializations", :format => :json

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :charges

  resources :order_profiles
  resources :users

  authenticated :user do
    root 'orders#new', as: "authenticated_root"
  end

  get 'welcome/about_us'
  get 'twilio/sms', defaults: { format: 'twiml' }

  post 'get_coffee' => 'home#get_coffee', as: :get_coffee

  post 'submit_order' => 'home#submit_order', as: :submit_order

  root 'welcome#index'

end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :order_profiles
  has_many :products
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form Test",
      :to => "coffeebreak305@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :order_profile
  has_one :runner
  has_one :user, through: :order_profile
end

app/models/order_profile.rb
class OrderProfile < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_one :business, through: :product
  validates :user, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :business
end

app/models/runner.rb
class Runner < ActiveRecord::Base
  has_many :orders

end

app/models/twilio_client.rb
class TwilioClient
  def self.send_text_message(order)
    runner = Runner.all.sample
    !runner ? (return 'No runner\'s avaliable' ) : nil
    number_to_send_to = runner.phone

    if Rails.env.test? || Rails.env.development?
      twilio_num = "3054400524"
    else
      twilio_num = ENV['TWILIO_NUM']
    end

    @client = Twilio::REST::Client.new
    @client.account.messages.create({
      :from => "+1#{twilio_num}",
      :to => '3058048507',
      :body => 'Yo go get coffe',
    })
    #puts "Sent message to #{runner.name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :order_profiles
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    #Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'user@stripe.com',
      :card => params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :desciprion => 'CoffeeBreak order',
      :currency => 'usd'
      )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @create = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Message delivered'
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end













end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order_profiles = OrderProfile.find_each.as_json
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save

        if Rails.env.test? || Rails.env.development?
          twilio_num = "7862071900"
        else
          twilio_num = ENV['TWILIO_NUM']
        end

        @client = Twilio::REST::Client.new
        @client.account.messages.create({
          :from => "+1#{twilio_num}",
          :to => '3058048507',
          :body => 'Yo go get coffe',
        })

        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params[:order].permit(:order_profile_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user, :order_profile]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def steps
  end
  def about_us
    @contact = Contact.new
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/receive_text_helper.rb
module ReceiveTextHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/send_text_helper.rb
module SendTextHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> CoffeeBreak | Get your fix.</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://checkout.stripe.com/checkout.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="<%=params[:controller]%>">
<!-- Begin notice and alerts flash messages -->
 <p class="notice col-xs-10 text-center hidden-lg hidden-md">
  <%= notice %>
</p>
<p class="alert col-xs-10 text-center">
  <%= alert %>
</p>
<!-- notice and alerts end -->

  <!-- Fixed navbar -->
<nav class="header-inner navbar navbar-default navbar-fixed-top">
  <div class="container" id="tempid"> <!-- added tempid for slight pre-reg css edits -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo-small" href="/">CoffeeBreak</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse nav-pad-right controls">
      <ul class="nav navbar-nav navbar-right nav-pad-right">
      <li><%= link_to "Home", root_path, class: "nav-pad-right" %></li>
      <li><%= link_to "About Us", welcome_about_us_path, class: "nav-pad-right" %></li>
        <li>
          <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-pad-right" %>
         <% else %>
            <%= link_to "Log In", new_user_session_path, class: "nav-pad-right" %>
          <% end %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<%= yield %>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script type="text/javascript">
  WebFontConfig = {
    google: { families: [ 'Raleway:400,200:latin', 'Raleway+Dots::latin', 'Cookie::latin' ] }
  };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
      '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })(); </script>
</body>
</html>